apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-config
  namespace: circle-banking-app
data:
  AWS_REGION: "us-east-1"
  LOCAL_ROUTING_NUM: "883745000"
  PUB_KEY_PATH: "/tmp/.ssh/publickey"
  PRIV_KEY_PATH: "/tmp/.ssh/privatekey"
  ENABLE_TRACING: "false"
  POD_NAMESPACE: "circle-banking-app"
  DYNAMODB_USERS_TABLE: "circle-banking-app-users-dev"
  DYNAMODB_CONTACTS_TABLE: "circle-banking-app-contacts-dev"
  DYNAMODB_TRANSACTIONS_TABLE: "circle-banking-app-transactions-dev"
  DYNAMODB_BALANCES_TABLE: "circle-banking-app-balances-dev"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-api-config
  namespace: circle-banking-app
data:
  TRANSACTIONS_API_ADDR: "ledgerwriter:8080"
  BALANCES_API_ADDR: "balancereader:8080"
  HISTORY_API_ADDR: "transactionhistory:8080"
  CONTACTS_API_ADDR: "contacts:8080"
  USERSERVICE_API_ADDR: "userservice:8080"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-data-config
  namespace: circle-banking-app
data:
  USE_DEMO_DATA: "True"
  DEMO_LOGIN_USERNAME: "testuser"
  DEMO_LOGIN_PASSWORD: "circleci"
