apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: circle-banking-app

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - config.yaml
  - ingress.yaml
  - frontend.yaml
  - userservice.yaml
  - contacts.yaml
  - balancereader.yaml
  - ledgerwriter.yaml
  - transactionhistory.yaml
  - loadgenerator.yaml
  - observability-services.yaml

images:
  - name: circle-banking-app/frontend
    newName: circle-banking-app/frontend
    newTag: latest
  - name: circle-banking-app/userservice
    newName: circle-banking-app/userservice
    newTag: latest
  - name: circle-banking-app/contacts
    newName: circle-banking-app/contacts
    newTag: latest
  - name: circle-banking-app/balancereader
    newName: circle-banking-app/balancereader
    newTag: latest
  - name: circle-banking-app/ledgerwriter
    newName: circle-banking-app/ledgerwriter
    newTag: latest
  - name: circle-banking-app/transactionhistory
    newName: circle-banking-app/transactionhistory
    newTag: latest
  - name: circle-banking-app/loadgenerator
    newName: circle-banking-app/loadgenerator
    newTag: latest
