version: 2.1

jobs:
  remove-label:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Remove Label from PR
          command: |
            echo "Removing run-ci label from the PR associated with this commit"
            PULL_REQUEST_NO=$(echo $CI_PULL_REQUEST | awk -F'/' '{print $(NF)}')
            GH_URL="https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/issues/$PULL_REQUEST_NO/labels/run-ci"
            curl -X DELETE -H "Authorization: token ${GITHUB_TOKEN}" -H "Accept: application/vnd.github.v3+json" "$GH_URL"


workflows:
  remove-pr-label:
    jobs:
      - remove-label:
          context: centralized-assest-github-envs
      
