version: 2.1

jobs:
  go-checkstyle:
    type: no-op

  go-test:
    type: no-op

  python-checkstyle:
    type: no-op

  python-test:
    type: no-op

workflows:
  open-pr:
    jobs:
      - go-checkstyle
      - go-test
      - python-checkstyle
      - python-test
