[project]
name = ""
version = "0.0.1"
requires-python = "~=3.12"
dependencies = [
    "pyyaml>=6.0.2",
    "requests",
]

[dependency-groups]
dev = []

[tool.uv]
package = false

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
