#!/bin/bash
# Quick start script for flaky test demo

echo "🚀 FLAKY TEST DEMO QUICK START"
echo "=============================="
echo ""
echo "Step 1: First, push your changes to CircleCI"
echo "---------------------------------------------"
echo "git push origin demo-nk-fe"
echo ""
echo "Step 2: Get your CircleCI API token"
echo "------------------------------------"
echo "Go to: https://app.circleci.com/settings/user/tokens"
echo "Create a new token and copy it"
echo ""
echo "Step 3: Set your token (replace with your actual token)"
echo "--------------------------------------------------------"
echo "export CIRCLECI_TOKEN='paste-your-token-here'"
echo ""
echo "Step 4: Run lightweight test pipelines (after setting token)"
echo "------------------------------------------------------------"
echo "./demo-assets/trigger-flaky-demo.sh 5"
echo ""
echo "This will trigger 5 test-only pipelines that:"
echo "  • Cost 80% less than full pipelines"
echo "  • Run in ~3 minutes each"
echo "  • Generate flaky test detection data"
echo ""
echo "Step 5: View results"
echo "--------------------" 
echo "open https://app.circleci.com/pipelines/github/AwesomeCICD/circle-banking-app?branch=demo-nk-fe"
echo ""
echo "After 3-5 runs, check Insights → Tests → Flaky tab"

