apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: ConfigMap
      name: environment-config
    patch: |
      - op: replace
        path: /data/DYNAMODB_USERS_TABLE
        value: circle-banking-app-users-dev
      - op: replace
        path: /data/DYNAMODB_CONTACTS_TABLE
        value: circle-banking-app-contacts-dev
      - op: replace
        path: /data/DYNAMODB_TRANSACTIONS_TABLE
        value: circle-banking-app-transactions-dev
      - op: replace
        path: /data/DYNAMODB_BALANCES_TABLE
        value: circle-banking-app-balances-dev
